### ISSUE TITLE
Running time error with ['ninja', '-v']

### ISSUE THREAD

**Issue by zelota556** [unlimblue/KNN_CUDA#16]
D:\Anaconda\envs\torch1.8.2\lib\site-packages\torch\utils\cpp_extension.py:304: UserWarning: Error checking compiler version for cl: 'utf-8' codec can't decode byte 0xd3 in position 0: invalid continuation byte
  warnings.warn(f'Error checking compiler version for {compiler}: {error}')
Traceback (most recent call last):
  File "D:\Anaconda\envs\torch1.8.2\lib\site-packages\torch\utils\cpp_extension.py", line 1673, in _run_ninja_build
    env=env)
  File "D:\Anaconda\envs\torch1.8.2\lib\subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
During handling of the above exception, another exception occurred:

**Comment by ANABUR920** [comment]
edit the D:\Anaconda\envs\torch1.8.2\lib\site-packages\torch\utils\cpp_extension.py" 

the '['ninja', '-v']'  in cpp_extension.py to  '['ninja', '--version']'

**Comment by basteran** [comment]
Thank you @ANABUR920 , you solved part of my problem, but why does this work?
